import { validateEnvironment } from "./schema";

export const serverEnvironment = validateEnvironment({
  APP_ENV: process.env.APP_ENV,
  PAYMENT_MODE: process.env.PAYMENT_MODE,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  PRIVATE_ADDRESS_KEY_VERSION: process.env.PRIVATE_ADDRESS_KEY_VERSION,
  PRIVATE_ADDRESS_KEY_V1_BASE64: process.env.PRIVATE_ADDRESS_KEY_V1_BASE64,
  INTERNAL_JOB_RECOVERY_SECRET: process.env.INTERNAL_JOB_RECOVERY_SECRET,
});
